### ISSUE TITLE
Redundant type hints

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/args#2]
```php
	/**
	 * The number of posts to query for. Use -1 to request all posts.
	 *
	 * @var int
	 */
	public int $posts_per_page;
```

How about telling its type only once?

```php
	/**
	 * The number of posts to query for. Use -1 to request all posts.
	 */
	public int $posts_per_page;
```

**Comment by johnbillion** [comment]
I added the type hints because I'm not sure if the typed properties are well supported in IDEs yet. I'll do some testing.

**Comment by szepeviktor** [comment]
Okay.

**Comment by szepeviktor** [comment]
@johnbillion A year ago in PhpStorm
https://blog.jetbrains.com/phpstorm/2019/07/phpstorm-2019-2-release/

**Comment by szepeviktor** [comment]
Eclipse ditto
https://bugs.eclipse.org/bugs/show_bug.cgi?id=551301

**Comment by szepeviktor** [comment]
Netbeans ditto
https://blogs.apache.org/netbeans/entry/php-7-4-support

**Comment by johnbillion** [comment]
Intelephense for VS Code 👍
https://github.com/bmewburn/vscode-intelephense/issues/770
