### ISSUE TITLE
PHP 8.1: PHP Deprecated:  Return type of Args\Shared\Base::offsetGet($offset)

### ISSUE THREAD

**Issue by thefrosty** [johnbillion/args#25]
PHP deprecation notice when running PHP 8.1.

```
PHP Deprecated:  Return type of Args\Shared\Base::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/local/wordpress/vendor/johnbillion/args/src/Shared/Base.php on line 47
```

- Tested w/ johnbillion/args (1.3.0 => 1.4.0)
- WordPress 6.0
- PHP 8.1

**Comment by thefrosty** [comment]
See core examples: https://github.com/WordPress/wordpress-develop/search?q=%23%5BReturnTypeWillChange%5D

**Comment by johnbillion** [comment]
Thanks, looks like I need to update the PHPUnit test config so that deprecated warnings cause the test run to fail.
