### ISSUE TITLE
Add tests that detect new and changed parameters

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/args#8]
Need a test suite that runs against WordPress nightly and detects new and changed parameters to the functions covered by this library.

**Comment by johnbillion** [comment]
https://make.wordpress.org/core/2022/01/05/new-capability-queries-in-wordpress-5-9/

**Comment by szepeviktor** [comment]
How could this manually written code be compared to WordPress source?

**Comment by johnbillion** [comment]
I'm planning on snapshot testing that produces a comparison between one version of WordPress and the next. I can then use that to alert me to changes that need to be made to this library.

**Comment by johnbillion** [comment]
"Fixed" in 27fc73c and 9c9aceb, though I still need to incorporate them into the CI.
